version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  webserver:
    image: apache/airflow:latest
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__SECRET_KEY: UQuKKeYIU/1E6+tPRxPGdg==
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/dags:/opt/airflow/logs
      - ./Datasets:/opt/airflow/datasets
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mynetwork

  scheduler:
    image: apache/airflow:latest
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__SECRET_KEY: UQuKKeYIU/1E6+tPRxPGdg==
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/dags:/opt/airflow/logs
      - ./Datasets:/opt/airflow/datasets
    command: scheduler
    depends_on:
      - postgres
      - webserver
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge